### ISSUE TITLE
Confusing audio instructions

### ISSUE THREAD

**Issue by cmcknight** [fgebhart/smart_alarm#2]
Hi!

I'm building the project per the instructions on the wiki. In the audio section, you mention that there are two low-band pass filters but that was a left-over from the original design that required two speakers. From that, I'm inferring that Fritzing diagram may not be correct. Is that correct and if so, could you post a correct diagram?

Thanks!

**Comment by fgebhart** [comment]
Hey,

if you build the smart alarm like shown in the Fritzing schematic, it will work. This means the Fritzing is correct, even though there is some extra information in it which you could leave out. Meaning the additional low-pass filter you mentioned. Since this project makes use of just one speaker, you also might just need to use one low-pass filter. Just make sure that the pwm audio signal of the Raspberry Pi (e.g. left) is connected to the same channel as the speaker (also left) in the amplifier. Sure thing I'll update the Fritzing to leave out the unneeded low-pass filter... sometime... in the future...

Let me know if there is still something unclear!

**Comment by fgebhart** [comment]
Updated Fritzing schematics and parts of the wiki. Now all correct!
check: https://github.com/fgebhart/smart_alarm/wiki#wiring
